default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ffs_development

test:
  <<: *default
  database: ffs_test

production:
  <<: *default
  database: ffs_production
