# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4597111d0e681339e469a93917a26a70aef5a617138a01da2e53950a8cc5e850eb375431a85a05cdb24f4b93c2fdf98ef1cfe6767fd01895271b2c2cdae7e9af

test:
  secret_key_base: 2f83363d22726d43338d5aa5dab97e56ded1c8b8fda9d1968c1f69a841e7a29f4ada50a240e053338f1703bb37dd0e7ba9def6dd08383b408b7e93c364e8831d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
